<?php
/**
 * Copyright (C) 2012 Slawomir Iwanczuk <slawomir@iwanczuk.co>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
?>
<script type="text/javascript">
//<![CDATA[
LightboxOptions = {
    fileLoadingImage: '<?php echo $this->getSkinUrl('images/loading.gif') ?>',
    fileBottomNavCloseImage: '<?php echo $this->getSkinUrl('images/closelabel.gif') ?>',
    overlayOpacity: 0.8,
    animate: true,
    resizeSpeed: 7,
    borderSize: 10,
    labelImage: '<?php echo $this->helper('lightboxgallery')->__('Image') ?>',
    labelOf: '<?php echo $this->helper('lightboxgallery')->__('of') ?>'
};
//]]>
</script>
